"""Revise


Revision ID: 4e9578332dc9
Revises: 6e1e12630347
Create Date: 2020-10-26 10:10:18.787745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e9578332dc9'
down_revision = '6e1e12630347'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rules', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rules', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
