"""empty message

Revision ID: 039849d578f1
Revises: 4e9578332dc9
Create Date: 2020-10-26 14:05:38.759153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '039849d578f1'
down_revision = '4e9578332dc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bots', sa.Column('is_draft', sa.Boolean(), nullable=False))
    op.drop_column('bots', 'developer_token')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bots', sa.Column('developer_token', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('bots', 'is_draft')
    # ### end Alembic commands ###
